### ISSUE TITLE
Heads-up: New Homebrew warning for your repo

### ISSUE THREAD

**Issue by skyzyx** [jzaleski/homebrew-apg#1]
I don't represent Homebrew — I'm just an end-user. Homebrew started warning recently:

```
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the jzaleski/jzaleski tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/jzaleski/homebrew-jzaleski/Formula/hadoop@2.7.1.rb:8
```

Wanted to give you a heads-up.

**Comment by jzaleski** [comment]
Thank you for the heads-up. This has been fixed with commit:
https://github.com/jzaleski/homebrew-jzaleski/commit/293130e9a24403c16ca1074cc1686df97b6ddda5

> brew install jzaleski/jzaleski/hadoop@2.7.1
==> Installing hadoop@2.7.1 from jzaleski/jzaleski
==> Downloading
http://archive.apache.org/dist/hadoop/common/hadoop-2.7.1/hadoop-2.7.1.tar.gz
########################################################################
100.0%
🍺  /usr/local/Cellar/hadoop@2.7.1/2.7.1: 6,301 files, 309.5MB, built in 12
seconds
